cluster.name: "sitebase-cluster"
node.name: "node-1"
network.host: 0.0.0.0
http.port: 9200

# Disabilita la sicurezza
plugins.security.disabled: true
plugins.security.ssl.transport.enabled: false
plugins.security.ssl.http.enabled: false

# Discovery single-node (utile in locale)
discovery.type: single-node
